---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/.config/docker/kavita/config:/config
      - /run/media/neiesc/Ultramassive/jellyfin-libraries/Books:/data
    ports:
      - 5000:5000
    restart: unless-stopped

