services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ~/.config/docker/jellyfin:/config
      - /var/cache/docker/jellyfin:/cache
      - type: bind
        source: /run/media/neiesc/Ultramassive/jellyfin-libraries/
        target: /media
        read_only: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'