services:
  polaris:
    image: registry.gitlab.com/connectical/container/polaris
    container_name: polaris
    ports:
      - "5050:5050"
    volumes:
      - /var/cache/docker/polaris:/var/cache/polaris
      - type: bind
        source: /run/media/neiesc/Ultramassive/jellyfin-libraries/Music
        target: /media
        read_only: true
    restart: 'unless-stopped'
