version: "3.9"

services:
  openaudible:
    image: openaudible/openaudible:latest
    container_name: openaudible
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${HOME}/OpenAudible:/config/OpenAudible"
